# Generated by Django 5.0.4 on 2024-04-30 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_version_delete_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['product', 'version_name'], 'verbose_name': 'Версия продукта', 'verbose_name_plural': 'Версия продуктов'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='version',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='catalog.product', verbose_name='продукт'),
        ),
    ]
